FROM php:8.3-fpm

RUN apt-get update && apt-get install -y --no-install-recommends \
    git \
    zlib1g-dev \
    libxml2-dev \
    libpng-dev \
    libzip-dev \
    vim curl debconf subversion git apt-transport-https apt-utils \
    build-essential locales acl mailutils wget nodejs zip unzip \
    gnupg gnupg1 gnupg2 \
    sudo \
    ssh \
    libpq-dev \
    && docker-php-ext-configure pgsql -with-pgsql=/usr/local/pgsql \
    && docker-php-ext-install \
    pdo_mysql \
    pgsql \
    pdo_pgsql \
    soap \
    zip \
    opcache \
    gd \
    intl

COPY ./opcache.ini /usr/local/etc/php/conf.d/

COPY ./custom.ini /usr/local/etc/php/conf.d/

RUN curl -sS https://getcomposer.org/installer | php && mv composer.phar /usr/local/bin/composer

RUN composer self-update
RUN wget --no-check-certificate https://phar.phpunit.de/phpunit-10.phar && \
    mv phpunit*.phar phpunit.phar && \
    chmod +x phpunit.phar && \
    mv phpunit.phar /usr/local/bin/phpunit

RUN usermod -u 1000 www-data

RUN usermod -a -G www-data root

RUN mkdir -p /var/www

RUN chown -R www-data:www-data /var/www

RUN mkdir -p /var/www/.composer

RUN chown -R www-data:www-data /var/www/.composer

WORKDIR /var/www/
